services:
  go-ssh-proxy:
    image: mahmoudetc/go-ssh-proxy:latest
    container_name: 'go-ssh-proxy'
    restart: unless-stopped
    volumes:
        - "./config.yaml:/app/config.yaml:ro"
    ports:
        - "2222:2222"
